
version: 2

models:
  - name: int__daily_average_rates
    description: "Exchange rates averaged for a particular day"
    columns:
      - name: date
        description: "The date of the exchange rate quote"
        tests:
          - not_null
      - name: source_currency
        description: "The source currency for the conversion"
        tests:
          - not_null
      - name: target_currency
        description: "The target currency for the conversion"
        tests:
          - not_null
      - name: rate
        description: "The daily average conversion rate"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - source_currency
            - target_currency
